name: 🚀 Deploy ke Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🔎 Checkout kode (non-shallow)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ambil seluruh history, penting!

      - name: 🔁 Push ke Hugging Face
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          git remote add hf https://yocelyn:${{ secrets.OOP_SATU }}@huggingface.co/spaces/yocelyn/praktekoopsatu
          git push -f hf main
